export type Vistas = "modulos" | "asistencia" | "comisiones";

export type ModuloColorProps = {
  primaryColor?: string;
  secondaryColor?: string;
  tertiaryColor?: string;
  primaryFrom?: string;
};

export type ModuloDashboard = {
  id: string;
  permiso: string;
  titulo: string;
  descripcion: string;
  ruta: string;
  iconoKey: string;
  iconoLottie?: string;
  lottieSpeed?: number;
  colorProps?: ModuloColorProps;
  categoria: string;
  subgrupo?: string;
};

export const TODOS_LOS_MODULOS: ModuloDashboard[] = [
  {
    id: "EDUCACION",
    permiso: "EDUCACION",
    titulo: "Política de Educación",
    descripcion: "Administre programas, niveles, maestros y alumnos.",
    ruta: "/sigem/educacion",
    iconoKey: "upgronsr",
    colorProps: { primaryColor: "#4bb3fd" },
    categoria: "Políticas Públicas",
  },
  {
    id: "FERTILIZANTE",
    permiso: "FERTILIZANTE",
    titulo: "Política de Desarrollo Económico Local",
    descripcion: "Gestione beneficiarios, entregas y estadísticas.",
    ruta: "/sigem/fertilizante/beneficiarios",
    iconoKey: "pdgwlefy",
    colorProps: { primaryFrom: "#ffc738", secondaryColor: "#4ade80" },
    categoria: "Políticas Públicas",
  },

  {
    id: "PERMISOS",
    permiso: "PERMISOS",
    titulo: "Mis Permisos y Acuerdos",
    descripcion: "Solicitud y control de permisos y acuerdos personales.",
    ruta: "/sigem/permisos",
    iconoKey: "ckbrgxtn",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión Propia",
  },
  {
    id: "ACTIVIDADES",
    permiso: "ACTIVIDADES",
    titulo: "Mis Actividades",
    descripcion: "Planificación y seguimiento de sus actividades.",
    ruta: "/sigem/actividades",
    iconoKey: "pmbbwkgy",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión Propia",
  },
  {
    id: "MIS_BIENES",
    permiso: "INVENTARIO",
    titulo: "Tarjeta de responsabilidad",
    descripcion: "Consulta y control de tus bienes asignados.",
    ruta: "/sigem/inventario/propias",
    iconoKey: "gbzbfgyf",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión Propia",
  },
  {
    id: "EVALUACIONES",
    permiso: "EVALUACIONES",
    titulo: "Evaluaciones de Desempeño",
    descripcion: "Autoevaluación y evaluación de su jefe o de su personal.",
    ruta: "/sigem/evaluaciones-desempeno",
    iconoKey: "svsvmktd",
    iconoLottie:
      "https://lottie.host/ffe0f547-a629-4478-9ac0-6d6a689ed440/xNhwc5Y81u.lottie",
    lottieSpeed: 1.2,
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión Propia",
  },
  {
    id: "SOLICITUDCOMBUSTIBLE",
    permiso: "SOLICITUDCOMBUSTIBLE",
    titulo: "Solicitar Cupón Combustible",
    descripcion: "Solicitud de cupones de combustible.",
    ruta: "/sigem/solicitud",
    iconoKey: "roogetvr",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión Propia",
  },
  {
    id: "PERMISOS_JEFE",
    permiso: "PERMISOS",
    titulo: "Supervisión de Permisos y Acuerdos",
    descripcion:
      "Avalar solicitudes de permisos y acuerdos de su equipo a cargo.",
    ruta: "/sigem/permisos/jefe",
    iconoKey: "ckbrgxtn",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión Jefe de Área",
  },
  {
    id: "ACTIVIDADES_JEFE",
    permiso: "ACTIVIDADES",
    titulo: "Supervisión de Actividades",
    descripcion: "Revise y gestione las actividades de su equipo.",
    ruta: "/sigem/actividades/jefe",
    iconoKey: "pmbbwkgy",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión Jefe de Área",
  },
  {
    id: "ASISTENCIA",
    permiso: "ASISTENCIA",
    titulo: "Gestión de Asistencia",
    descripcion: "Supervise la asistencia de su equipo.",
    ruta: "/sigem/asistencias",
    iconoKey: "sgtmgpft",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión Jefe de Área",
  },
  {
    id: "COMISIONES_JEFE",
    permiso: "COMISIONES",
    titulo: "Gestión de Comisiones",
    descripcion: "Gestione las comisiones de su área.",
    ruta: "/sigem/comisiones/JEFE",
    iconoKey: "vqkaxtlm",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión Jefe de Área",
  },
  {
    id: "SOLICITUDES_JEFE",
    permiso: "SOLICITUDES_JEFE",
    titulo: "Solicitudes Inter-Oficinas",
    descripcion: "Revise y gestione las solicitudes de Inter-Oficinas.",
    ruta: "/sigem/solicitudes/jefes",
    iconoKey: "dnkhszms",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión Jefe de Área",
  },
  {
    id: "INVENTARIO_JEFE",
    permiso: "INVENTARIO",
    titulo: "Tarjetas de responsabilidad de Mi Equipo",
    descripcion: "Supervise los bienes de su dependencia y personal a cargo.",
    ruta: "/sigem/inventario/jefe",
    iconoKey: "gbzbfgyf",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión Jefe de Área",
  },
  {
    id: "PERMISOS_GESTION",
    permiso: "RRHH",
    titulo: "Administración de Permisos y Acuerdos",
    descripcion: "Aprobación final y gestión de historial.",
    ruta: "/sigem/permisos/rrhh",
    iconoKey: "ckbrgxtn",
    categoria: "Gestión Administrativa",
    subgrupo: "Recursos Humanos",
  },
  {
    id: "ACTIVIDADES_GESTION",
    permiso: "RRHH",
    titulo: "Administración de Actividades",
    descripcion: "Visión global de actividades municipales.",
    ruta: "/sigem/actividades/rrhh",
    iconoKey: "pmbbwkgy",
    categoria: "Gestión Administrativa",
    subgrupo: "Recursos Humanos",
  },
  {
    id: "RRHH",
    permiso: "RRHH",
    titulo: "Gestión de Personal",
    descripcion: "Gestione los datos y el historial de los empleados.",
    ruta: "/sigem/admin/users",
    iconoKey: "daeumrty",
    categoria: "Gestión Administrativa",
    subgrupo: "Recursos Humanos",
  },
  {
    id: "COMISIONES_RRHH",
    permiso: "COMISIONES",
    titulo: "Gestión de Comisiones Global",
    descripcion: "Cree, apruebe y gestione las comisiones.",
    ruta: "/sigem/comisiones/RRHH",
    iconoKey: "vqkaxtlm",
    categoria: "Gestión Administrativa",
    subgrupo: "Recursos Humanos",
  },
  {
    id: "ORGANOS_RRHH",
    permiso: "ORGANOS",
    titulo: "Estructura Organizacional",
    descripcion: "Gestione dependencias y jerarquías.",
    ruta: "/sigem/admin/dependencias",
    iconoKey: "vrxmikgh",
    colorProps: { primaryColor: "#ebe6ef", secondaryColor: "#b26836" },
    categoria: "Gestión Administrativa",
    subgrupo: "Recursos Humanos",
  },
  {
    id: "EVALUACIONES_GESTION",
    permiso: "RRHH",
    titulo: "Evaluaciones de Desempeño",
    descripcion: "Formularios, asignaciones y resultados de todo el personal.",
    ruta: "/sigem/evaluaciones-desempeno/rrhh",
    iconoKey: "svsvmktd",
    iconoLottie:
      "https://lottie.host/ffe0f547-a629-4478-9ac0-6d6a689ed440/xNhwc5Y81u.lottie",
    lottieSpeed: 1.2,
    categoria: "Gestión Administrativa",
    subgrupo: "Recursos Humanos",
  },
  {
    id: "AGENDA_CONCEJO",
    permiso: "AGENDA_CONCEJO",
    titulo: "Agenda de Concejo",
    descripcion: "Consulte y gestione las próximas reuniones.",
    ruta: "/sigem/concejo/agenda/",
    iconoKey: "yxsbonud",
    colorProps: { primaryColor: "#ebe6ef", secondaryColor: "#4bb3fd" },
    categoria: "Gestión Administrativa",
    subgrupo: "Concejo Municipal",
  },
  {
    id: "ORGANOS_CONCEJO",
    permiso: "ORGANOS",
    titulo: "Estructura Organizacional",
    descripcion: "Vista de estructura y órganos municipales.",
    ruta: "/sigem/admin/dependencias",
    iconoKey: "vrxmikgh",
    colorProps: { primaryColor: "#ebe6ef", secondaryColor: "#b26836" },
    categoria: "Gestión Administrativa",
    subgrupo: "Concejo Municipal",
  },

  {
    id: "GESTION_COMBUSTIBLE",
    permiso: "COMBUSTIBLE",
    titulo: "Gestión de Combustible",
    descripcion: "Control de vales y consumo de combustible.",
    ruta: "/sigem/combustible",
    iconoKey: "whcpieow",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión de Recursos Municipales",
  },
  {
    id: "CONTRATOS_COMBUSTIBLE",
    permiso: "CONTRATOS",
    titulo: "Contratos de Combustible",
    descripcion: "Seguimiento de contratos con gasolineras.",
    ruta: "/sigem/combustible/contrato",
    iconoKey: "pxglrdrs",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión de Recursos Municipales",
  },
  {
    id: "INVENTARIO_GENERAL",
    permiso: "INVENTARIO",
    titulo: "Inventario de bienes municipales",
    descripcion:
      "Gestión completa y centralizada de todos los bienes municipales.",
    ruta: "/sigem/inventario/general",
    iconoKey: "gbzbfgyf",
    categoria: "Gestión Administrativa",
    subgrupo: "Gestión de Recursos Municipales",
  },
  {
    id: "SOLICITUDES_LAMARAS",
    permiso: "SOLICITUDES_LAMARAS",
    titulo: "Solicitudes de Lámparas",
    descripcion:
      "Gestione el ingreso y seguimiento de Solicitudes de Lámparas.",
    ruta: "/sigem/solicitudes/lamparas",
    iconoKey: "cuywyxhb",
    categoria: "Gestión Administrativa",
    subgrupo: "Recepción",
  },
  {
    id: "SOLICITUDES_MOBILIARIO",
    permiso: "SOLICITUDES_MOBILIARIO",
    titulo: "Solicitudes de Mobiliario",
    descripcion:
      "Gestione el ingreso y seguimiento de Solicitudes de Mobiliario.",
    ruta: "/sigem/solicitudes/mobiliario",
    iconoKey: "qretqoqe",
    colorProps: { primaryColor: "#242424", secondaryColor: "#b4b4b4" },
    categoria: "Gestión Administrativa",
    subgrupo: "Recepción",
  },
  {
    id: "DEV",
    permiso: "SUPER",
    titulo: "Mensajes del Sistema",
    descripcion: "Gestione avisos y notificaciones globales del sistema.",
    ruta: "/sigem/dev",
    iconoKey: "bsmkjadb",
    categoria: "Gestión Administrativa",
  },
];
